title: Lizzy's Blog
email: lizainslie16@gmail.com
description: >-
  Welcome to my little corner of the internet! Here, I write
  about whatever I feel like writing. I mostly enjoy writing
  about tech, humor, and music, but I try not to limit myself
  to just a few things. I am transgender (MTF), and 18 years
  of age.
baseurl: "/blog"
url: https://lizainslie.dev
plugins:
  - jekyll-feed
  - jekyll-paginate
permalink: /:year/:month/:day/:title/
destination: ./build
paginate: 5
twitter_username: LizzyReborn
github_username: LizAinslie